# Generated by Django 4.2.3 on 2023-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_cusine', models.CharField(max_length=50, null=True)),
                ('favourite_sports', models.CharField(max_length=50, null=True)),
                ('favourite_book', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
